import test from "node:test";
import assert from "node:assert/strict";
import { createClient } from "redis";
import {
  signUp,
  executeRpc,
  executeDbRequest,
  prospectFeedbackForOrganization,
} from "../src/integrations/render/state.server.ts";

test("a shared team workspace has private datasets for each signed-in user", async () => {
  const redis = createClient({ url: process.env.REDIS_URL });
  await redis.connect();
  await redis.del("clientsource:state:v1");
  try {
    const { user: owner } = await signUp("owner@example.test", "password-unique-1", "Owner");
    const created = await executeRpc(owner.id, "create_workspace", { org_name: "Isolation Test" });
    assert.equal(created.error, null);
    const organization_id = created.data;
    const invitation = await executeRpc(owner.id, "create_invite", { email: "member@example.test", role: "member" });
    assert.equal(invitation.error, null);
    const { user: member } = await signUp("member@example.test", "password-unique-2", "Member", invitation.data.token);

    const insertCompany = (userId, name, extras = {}) => executeDbRequest(userId, {
      table: "companies", action: "insert", returning: true,
      payload: { organization_id, name, website: "example.com", ...extras },
    });
    const list = (userId, table) => executeDbRequest(userId, {
      table, action: "select", countExact: true,
    });

    const ownerInsert = await insertCompany(owner.id, "Owner company");
    assert.equal(ownerInsert.error, null);
    const ownerId = ownerInsert.data[0].id;
    assert.equal((await list(member.id, "companies")).data.length, 0, "new member must start empty");

    const memberInsert = await insertCompany(member.id, "Member company", {
      id: ownerId, owner_user_id: owner.id,
    });
    assert.equal(memberInsert.error, null);
    assert.notEqual(memberInsert.data[0].id, ownerId, "record IDs must be generated by the server");
    assert.equal(memberInsert.data[0].owner_user_id, member.id, "ownership must ignore client payloads");
    assert.deepEqual((await list(owner.id, "companies")).data.map((c) => c.name), ["Owner company"]);
    assert.deepEqual((await list(member.id, "companies")).data.map((c) => c.name), ["Member company"]);

    const reference = await executeDbRequest(member.id, {
      table: "contacts", action: "insert",
      payload: { organization_id, company_id: ownerId, full_name: "Cross-account contact" },
    });
    assert.equal(reference.error?.code, "23503", "foreign-user references must fail");

    const patch = await executeDbRequest(member.id, {
      table: "companies", action: "update", returning: true,
      filters: [{ op: "eq", column: "id", value: ownerId }],
      payload: { name: "Tampered" },
    });
    assert.equal(patch.error, null);
    assert.deepEqual(patch.data, [], "other users' records cannot be updated");

    const remove = await executeDbRequest(member.id, {
      table: "companies", action: "delete", returning: true,
      filters: [{ op: "eq", column: "id", value: ownerId }],
    });
    assert.equal(remove.error, null);
    assert.deepEqual(remove.data, [], "other users' records cannot be deleted");
    assert.equal((await list(owner.id, "companies")).data[0].name, "Owner company");

    const createDossier = (userId) => executeDbRequest(userId, {
      table: "prospect_dossiers", action: "insert", returning: true,
      payload: {
        organization_id, domain: "target.example", sender_website: "https://sender.example",
        company_name: "Example Target", outcome: "interested", stage: "qualified",
      },
    });
    assert.equal((await createDossier(owner.id)).error, null);
    assert.equal((await list(member.id, "prospect_dossiers")).data.length, 0);
    assert.equal((await createDossier(member.id)).error, null, "same prospect domain is allowed for different users");
    assert.equal((await list(owner.id, "prospect_dossiers")).data.length, 1);
    assert.equal((await list(member.id, "prospect_dossiers")).data.length, 1);
    assert.equal((await prospectFeedbackForOrganization(organization_id, owner.id)).samples, 1);
    assert.equal((await prospectFeedbackForOrganization(organization_id, member.id)).samples, 1);

    // Historical shared rows have no reliable creator: retain them but never show them as a user's own.
    const existing = JSON.parse(await redis.get("clientsource:state:v1"));
    existing.companies.push({
      id: "legacy-unowned", organization_id, name: "Legacy shared row",
      website: null, status: "new", created_at: new Date().toISOString(),
    });
    await redis.set("clientsource:state:v1", JSON.stringify(existing));
    assert.equal((await list(owner.id, "companies")).data.length, 1);
    assert.equal((await list(member.id, "companies")).data.length, 1);
    assert.ok(JSON.parse(await redis.get("clientsource:state:v1")).companies.some((c) => c.id === "legacy-unowned"),
      "legacy records are preserved");
  } finally {
    await redis.del("clientsource:state:v1");
    await redis.quit();
  }
});
