/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppCapabilitiesRouteImport } from './routes/_authenticated/_app/capabilities'
import { Route as AuthenticatedAppCompaniesRouteImport } from './routes/_authenticated/_app/companies'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/_app/contacts'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppImportRouteImport } from './routes/_authenticated/_app/import'
import { Route as AuthenticatedAppMembersRouteImport } from './routes/_authenticated/_app/members'
import { Route as AuthenticatedAppProspectRouteImport } from './routes/_authenticated/_app/prospect'
import { Route as AuthenticatedAppProspectsRouteImport } from './routes/_authenticated/_app/prospects'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppTendersRouteImport } from './routes/_authenticated/_app/tenders'
import { Route as ApiTendersCronRouteImport } from './routes/api.tenders.cron'
import { Route as ApiTendersSourceHealthRouteImport } from './routes/api.tenders.source-health'
import { Route as AuthenticatedAppTendersTenderIdRouteImport } from './routes/_authenticated/_app/tenders.$tenderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCapabilitiesRoute =
  AuthenticatedAppCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCompaniesRoute =
  AuthenticatedAppCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportRoute = AuthenticatedAppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMembersRoute = AuthenticatedAppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProspectRoute =
  AuthenticatedAppProspectRouteImport.update({
    id: '/prospect',
    path: '/prospect',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProspectsRoute =
  AuthenticatedAppProspectsRouteImport.update({
    id: '/prospects',
    path: '/prospects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTendersRoute = AuthenticatedAppTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiTendersCronRoute = ApiTendersCronRouteImport.update({
  id: '/api/tenders/cron',
  path: '/api/tenders/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTendersSourceHealthRoute = ApiTendersSourceHealthRouteImport.update({
  id: '/api/tenders/source-health',
  path: '/api/tenders/source-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTendersTenderIdRoute =
  AuthenticatedAppTendersTenderIdRouteImport.update({
    id: '/$tenderId',
    path: '/$tenderId',
    getParentRoute: () => AuthenticatedAppTendersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/capabilities': typeof AuthenticatedAppCapabilitiesRoute
  '/companies': typeof AuthenticatedAppCompaniesRoute
  '/contacts': typeof AuthenticatedAppContactsRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/import': typeof AuthenticatedAppImportRoute
  '/members': typeof AuthenticatedAppMembersRoute
  '/prospect': typeof AuthenticatedAppProspectRoute
  '/prospects': typeof AuthenticatedAppProspectsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tenders': typeof AuthenticatedAppTendersRouteWithChildren
  '/api/tenders/cron': typeof ApiTendersCronRoute
  '/api/tenders/source-health': typeof ApiTendersSourceHealthRoute
  '/tenders/$tenderId': typeof AuthenticatedAppTendersTenderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/capabilities': typeof AuthenticatedAppCapabilitiesRoute
  '/companies': typeof AuthenticatedAppCompaniesRoute
  '/contacts': typeof AuthenticatedAppContactsRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/import': typeof AuthenticatedAppImportRoute
  '/members': typeof AuthenticatedAppMembersRoute
  '/prospect': typeof AuthenticatedAppProspectRoute
  '/prospects': typeof AuthenticatedAppProspectsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tenders': typeof AuthenticatedAppTendersRouteWithChildren
  '/api/tenders/cron': typeof ApiTendersCronRoute
  '/api/tenders/source-health': typeof ApiTendersSourceHealthRoute
  '/tenders/$tenderId': typeof AuthenticatedAppTendersTenderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/health': typeof HealthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/capabilities': typeof AuthenticatedAppCapabilitiesRoute
  '/_authenticated/_app/companies': typeof AuthenticatedAppCompaniesRoute
  '/_authenticated/_app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/import': typeof AuthenticatedAppImportRoute
  '/_authenticated/_app/members': typeof AuthenticatedAppMembersRoute
  '/_authenticated/_app/prospect': typeof AuthenticatedAppProspectRoute
  '/_authenticated/_app/prospects': typeof AuthenticatedAppProspectsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/tenders': typeof AuthenticatedAppTendersRouteWithChildren
  '/api/tenders/cron': typeof ApiTendersCronRoute
  '/api/tenders/source-health': typeof ApiTendersSourceHealthRoute
  '/_authenticated/_app/tenders/$tenderId': typeof AuthenticatedAppTendersTenderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/reset-password'
    | '/onboarding'
    | '/capabilities'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/import'
    | '/members'
    | '/prospect'
    | '/prospects'
    | '/settings'
    | '/tenders'
    | '/api/tenders/cron'
    | '/api/tenders/source-health'
    | '/tenders/$tenderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/health'
    | '/reset-password'
    | '/onboarding'
    | '/capabilities'
    | '/companies'
    | '/contacts'
    | '/dashboard'
    | '/import'
    | '/members'
    | '/prospect'
    | '/prospects'
    | '/settings'
    | '/tenders'
    | '/api/tenders/cron'
    | '/api/tenders/source-health'
    | '/tenders/$tenderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/health'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/capabilities'
    | '/_authenticated/_app/companies'
    | '/_authenticated/_app/contacts'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/import'
    | '/_authenticated/_app/members'
    | '/_authenticated/_app/prospect'
    | '/_authenticated/_app/prospects'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/tenders'
    | '/api/tenders/cron'
    | '/api/tenders/source-health'
    | '/_authenticated/_app/tenders/$tenderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HealthRoute: typeof HealthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTendersCronRoute: typeof ApiTendersCronRoute
  ApiTendersSourceHealthRoute: typeof ApiTendersSourceHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/capabilities': {
      id: '/_authenticated/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AuthenticatedAppCapabilitiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/companies': {
      id: '/_authenticated/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedAppCompaniesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/contacts': {
      id: '/_authenticated/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/import': {
      id: '/_authenticated/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/members': {
      id: '/_authenticated/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedAppMembersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/prospect': {
      id: '/_authenticated/_app/prospect'
      path: '/prospect'
      fullPath: '/prospect'
      preLoaderRoute: typeof AuthenticatedAppProspectRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/prospects': {
      id: '/_authenticated/_app/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedAppProspectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/tenders': {
      id: '/_authenticated/_app/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AuthenticatedAppTendersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/tenders/cron': {
      id: '/api/tenders/cron'
      path: '/api/tenders/cron'
      fullPath: '/api/tenders/cron'
      preLoaderRoute: typeof ApiTendersCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenders/source-health': {
      id: '/api/tenders/source-health'
      path: '/api/tenders/source-health'
      fullPath: '/api/tenders/source-health'
      preLoaderRoute: typeof ApiTendersSourceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app/tenders/$tenderId': {
      id: '/_authenticated/_app/tenders/$tenderId'
      path: '/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof AuthenticatedAppTendersTenderIdRouteImport
      parentRoute: typeof AuthenticatedAppTendersRoute
    }
  }
}

interface AuthenticatedAppTendersRouteChildren {
  AuthenticatedAppTendersTenderIdRoute: typeof AuthenticatedAppTendersTenderIdRoute
}

const AuthenticatedAppTendersRouteChildren: AuthenticatedAppTendersRouteChildren =
  {
    AuthenticatedAppTendersTenderIdRoute: AuthenticatedAppTendersTenderIdRoute,
  }

const AuthenticatedAppTendersRouteWithChildren =
  AuthenticatedAppTendersRoute._addFileChildren(
    AuthenticatedAppTendersRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCapabilitiesRoute: typeof AuthenticatedAppCapabilitiesRoute
  AuthenticatedAppCompaniesRoute: typeof AuthenticatedAppCompaniesRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppImportRoute: typeof AuthenticatedAppImportRoute
  AuthenticatedAppMembersRoute: typeof AuthenticatedAppMembersRoute
  AuthenticatedAppProspectRoute: typeof AuthenticatedAppProspectRoute
  AuthenticatedAppProspectsRoute: typeof AuthenticatedAppProspectsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTendersRoute: typeof AuthenticatedAppTendersRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCapabilitiesRoute: AuthenticatedAppCapabilitiesRoute,
  AuthenticatedAppCompaniesRoute: AuthenticatedAppCompaniesRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppImportRoute: AuthenticatedAppImportRoute,
  AuthenticatedAppMembersRoute: AuthenticatedAppMembersRoute,
  AuthenticatedAppProspectRoute: AuthenticatedAppProspectRoute,
  AuthenticatedAppProspectsRoute: AuthenticatedAppProspectsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTendersRoute: AuthenticatedAppTendersRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HealthRoute: HealthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTendersCronRoute: ApiTendersCronRoute,
  ApiTendersSourceHealthRoute: ApiTendersSourceHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
